# Conv2D Layers

convolution 연산이 어떻게 진행되고 weight와 bias 그리고 window shape들이 어떻게 형성되는지 확인해보자.

conv layer에서 사용되는 correlation 연산을 numpy를 활용하여 구현해보고

tensorflow에 있는 conv2D의 결과값과 같은지 확인해보자.

## Shapes of Conv Layers

In [8]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28,28,3 # C 수를 바꿔주면 어떻게 shape값이 바뀌는 지 확인해보자
n_filter = 1 # filter값이 바뀌면 어느 shape부분이 바뀌는 지 확인해보자.
f_size = 3 # filter size를 바꾸면 어디가 바뀌는지 확인해보자.

images = tf.random.uniform(minval=0,maxval=1,shape=((N,n_H,n_W,n_C)))

conv = Conv2D(filters=n_filter, kernel_size = k_size)

y = conv(images)

W,B = conv.get_weights()

print(images.shape)
print(W.shape)
print(B.shape)
print(y.shape)

(1, 28, 28, 3)
(3, 3, 3, 1)
(1,)
(1, 26, 26, 1)


## Correlation Calculation

In [24]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W,n_C = 1, 5,5,1
n_filter = 1
k_size = 3 #window 크기

images = tf.random.uniform(minval=0,maxval=1,
                          shape= ((N,n_H,n_W,n_C))) 

conv = Conv2D(filters=n_filter, kernel_size = k_size)

y = conv(images)
print("Y(tensorflow): \n",y.numpy().squeeze()) #squeeze함수를 사용하면 y shape가 최소한의 차원으로 바뀐다.
W,B=conv.get_weights()

#####
images = images.numpy().squeeze()
W = W.squeeze()

# print(images.shape)
# print(W.shape)
# print(B.shape)

y_man = np.zeros(shape = (n_H - k_size + 1 ,n_W - k_size + 1))

for i in range(n_H -k_size+1):
    for j in range(n_W -k_size+ 1): #window의 초기 인덱스를 잡아주는 것이 i,j이다.
        window = images[i:i+k_size,j:j+k_size] 
        y_man[i,j] = np.sum(window*W)+B #이 부분에서 conv 연산이 진행되는 것과 동일한 과정을 갖는다.
        
        #print(window.shape)
print("Y(Manual): \n",y_man)

Y(tensorflow): 
 [[ 0.6153333   0.6170325   0.4753493 ]
 [ 0.42878878  0.26073298  0.13926238]
 [-0.1030992  -0.12954181  0.3983576 ]]
Y(Manual): 
 [[ 0.61533332  0.61703265  0.47534931]
 [ 0.42878878  0.26073298  0.13926229]
 [-0.10309925 -0.12954181  0.39835763]]


## Correlation with n-channel

In [25]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W,n_C = 1, 5,5,3
n_filter = 1
k_size = 3 #window 크기

images = tf.random.uniform(minval=0,maxval=1,
                          shape= ((N,n_H,n_W,n_C))) 

conv = Conv2D(filters=n_filter, kernel_size = k_size)

y = conv(images)
print("Y(tensorflow): \n",y.numpy().squeeze()) #squeeze함수를 사용하면 y shape가 최소한의 차원으로 바뀐다.
W,B=conv.get_weights()

#####
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape = (n_H - k_size + 1 ,n_W - k_size + 1))

for i in range(n_H -k_size+1):
    for j in range(n_W -k_size+ 1): #window의 초기 인덱스를 잡아주는 것이 i,j이다.
        window = images[i:i+k_size,j:j+k_size,:] 
        y_man[i,j] = np.sum(window*W)+B #이 부분에서 conv 연산이 진행되는 것과 동일한 과정을 갖는다.
        
        #print(window.shape)
print("Y(Manual): \n",y_man)

#tensorflow의 Conv2D연산을 직접 numpy를 활용하여 구현하여 conv연산이 어떻게 진행되는지와 구조를 코드로 확인 가능하였다.

Y(tensorflow): 
 [[0.7962659  0.2248787  1.3366759 ]
 [0.95532846 0.98810637 0.5097714 ]
 [0.5575899  0.56069964 0.7777792 ]]
Y(Manual): 
 [[0.79626608 0.22487867 1.33667576]
 [0.95532858 0.98810637 0.50977135]
 [0.55758977 0.56069964 0.77777922]]
